[build]
builder = "NIXPACKS"

[deploy]
startCommand = "uvicorn main:app --host 0.0.0.0 --port $PORT"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[variables]
DATABASE_URL = "sqlite:///./data/pixel_todos.db"
FRONTEND_DIR = "frontend"
ENVIRONMENT = "production"
PORT = "8080"